- hosts: user
  sudo: true
  remote_user: ubuntu
  tasks:
  - name: Update cache
    apt: update_cache=yes
  - name: Install Pip
    apt: name=python-setuptools state=present
  - name: Python
    apt: name=python-dev state=present
  - name: Python2
    apt: name=python-pip state=present
  - name: Instalar MongoDB
    apt: name=mongodb state=present
  - name: Instalamos pyTelegramBotAPI
    pip: name=pyTelegramBotAPI




